name: Build

defaults:
  run:
    shell: bash
    working-directory: ./codebase/rdicidr-0.1.0

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: '15.0.1'
      - name: Install
        run: npm install
      - name: Lint
        run: npm run lint
      - name: Format
        run: npm run prettier
      - name: Test
        run: CI=true npm run test
      - name: Build
        run: npm run build