name: CI

on:
  push

jobs:
  my_job:
    name: CI
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Node.js environment
      uses: actions/setup-node@v4.0.3
      with:
        node-version: '14'

    - name: NPM install cache
    # You may pin to the exact commit or the version.
    # uses: c-hive/gha-npm-cache@2de807f96074eec2c36c2d321c20724cd04112dd
      uses: c-hive/gha-npm-cache@v1
      with:
    # Directory containing package-lock.json
        directory: codebase/rdicidr-0.1.0

    - name: Install dependencies 
      run:  npm install codebase/rdicidr-0.1.0

    - name: Linter (ESLint) 
      run:  npm run lint codebase/rdicidr-0.1.0

    - name: Formatter (Prettier) 
      run:  npm run prettier codebase/rdicidr-0.1.0

    - name: Test (Jest) CI=true 
      run:  npm run test codebase/rdicidr-0.1.0

    - name: Build 
      run:  npm run build codebase/rdicidr-0.1.0

          


