name: "Test Branch Name"
on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
  # check branch name
jobs:
  test_job:
    runs-on: ubuntu-latest
    name: A job to test branch name
    steps:
      - uses: mhm0ud/github-actions-gitflow@v1
